In [11]:
import numpy as np


In [12]:
arr =np.array([[19,23,89],[19,80,80],[1,8,3]])

In [13]:
print(arr.dtype)

int64


In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
print(arr.shape)

(3, 3)


In [19]:
print(arr.ndim)

2


In [17]:
# Array Slicing :

In [20]:
arr[1:]

array([[19, 80, 80],
       [ 1,  8,  3]])

In [21]:
# Slicing for particular row or number

In [26]:
arr[1,...]

array([19, 80, 80])

In [28]:
arr[...,1]

array([23, 80,  8])